#!/bin/sh
#MISE description="Build the cli"
#USAGE flag "-d --dev" help="Build development version"
#USAGE flag "-c --clean" help="Clean the build directory before building"
#USAGE flag "-v --version <version>" help="Set the version of the build"
#USAGE flag "-o --os <os>" help="Set the target OS"
#USAGE flag "-a --arch <arch>" help="Set the target architecture"

if test "$usage_clean" = "true"; then
  rm -rf dist
  mkdir -p dist
fi

if test -z "$usage_version"; then
  version="$(git describe --tags --always --dirty)"
else
  version="$usage_version"
fi

commit="$(git rev-parse --short HEAD)"
date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
os="${usage_os:-linux}"
arch="${usage_arch:-amd64}"

ldflags="-X main.version=$version -X main.commit=$commit -X main.date=$date"
if test ! "$usage_dev" = "true"; then
  ldflags="$ldflags -s -w"
fi

printf "Building version %s for %s/%s\n" "$version" "$os" "$arch"
GOOS=$os GOARCH=$arch go build -ldflags "$ldflags" -o "dist/constructor-$os-$arch" .