#!/bin/sh
#MISE description="Detect the next version of the cli"
#USAGE flag "-l --local" help="Provide when running locally"

rm -rf .version
rm -rf .version-unreleased

srOutfile=$(mktemp)

semantic-release --dry --version-file --allow-no-changes ${usage_local:+-t} ${usage_local:+"$(gh auth token)"} ${usage_local:+--provider-opt} ${usage_local:+'slug=MadsRC/constructor'} ${usage_local:+--no-ci} >> $srOutfile 2>&1

if [ $? -ne 0 ]; then
  printf "Something went wrong, dumping 'semantic-release' output:\n"
  cat "$srOutfile"
  exit 2
fi

if test -f .version-unreleased; then
  cat .version-unreleased
  exit 0
else
  printf "No new version detected\n"
  exit 1
fi